version: "3.4"

services:
  app:
    image: nextcloud
    networks:
      - fitec
    volumes:
      - app_data:/var/www/html/data
      - app_config:/var/www/html/config  
    ports:
      - 9000:80
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud1234
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin1234

  db:
    image: postgres
    networks:
      - fitec
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud1234
      POSTGRES_DB: nextcloud

  check:
    image: adminer
    networks:
      - fitec
    ports:
      - 8080:8080

  LB:
    build: haproxy
    image: haproxy_configured:latest
    networks:
      - fitec
    ports:
      - 80:80
    
networks:
  fitec:

volumes:
  app_data:
  db_data:
  app_config:
